sudo: required

language: cpp

compiler:
  - gcc
  - clang

#install:
#  - sudo apt-get install libboost-all-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
